repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
    # Run the formatter.
    -   id: ruff-format
        args: [--line-length=120]
    # Run the linter.
    -   id: ruff
        args: [--fix] 